// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrMuQfUEQtgK0ekQ52BBvuXRQATyHc_jU',
    appId: '1:679903724700:web:5d779b63c4c9b6c68c1959',
    messagingSenderId: '679903724700',
    projectId: 'test-app-70f8f',
    authDomain: 'test-app-70f8f.firebaseapp.com',
    storageBucket: 'test-app-70f8f.appspot.com',
    measurementId: 'G-MDCPRJ6DHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzpP82Z0p6MAFzXl9dQI2AOTD2_ssr99E',
    appId: '1:679903724700:android:cb670071da0d507b8c1959',
    messagingSenderId: '679903724700',
    projectId: 'test-app-70f8f',
    storageBucket: 'test-app-70f8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOpHmSMg-7Xgfuw62AFClN7vIseduIeCE',
    appId: '1:679903724700:ios:439b0f0b477d02fa8c1959',
    messagingSenderId: '679903724700',
    projectId: 'test-app-70f8f',
    storageBucket: 'test-app-70f8f.appspot.com',
    iosClientId: '679903724700-suc3095sqvmjteh1q5dakcujqdhgn0jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOpHmSMg-7Xgfuw62AFClN7vIseduIeCE',
    appId: '1:679903724700:ios:439b0f0b477d02fa8c1959',
    messagingSenderId: '679903724700',
    projectId: 'test-app-70f8f',
    storageBucket: 'test-app-70f8f.appspot.com',
    iosClientId: '679903724700-suc3095sqvmjteh1q5dakcujqdhgn0jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokTest',
  );
}
